# Software Versions {#software}

SPEAQeasy makes use of several external bioinformatics software tools. The pipeline additionally supports the use of these tools via docker containers- this section also documents the docker images used in this mode.

Here is the full list of software used by this pipeline:
    
Software | Version | Command used by the pipeline |
|:-------------:| -----:| -----: |
|[bcftools](http://www.htslib.org/download/) | 1.10.2 | `bcftools` |
|[fastQC](http://www.bioinformatics.babraham.ac.uk/projects/fastqc) | 0.11.8 | `fastqc` |
|[hisat2](https://ccb.jhu.edu/software/hisat2/manual.shtml#obtaining-hisat2) | 2.2.1 | `hisat2`, `hisat2-build` |
|[htslib](http://www.htslib.org/download/) | 1.10.2 | `tabix` |
|[java](http://www.oracle.com/technetwork/java/javase/downloads/index.html) | 8+ | `java` |
|[kallisto](https://pachterlab.github.io/kallisto/source) | 0.46.1 | `kallisto` |
|[nextflow](https://www.nextflow.io/docs/latest/getstarted.html) | >=0.27.0 (tested with 20.01.0) | `nextflow` |
|[R](https://cran.r-project.org/bin/linux/ubuntu/README.html#installation) | 3.6 | `Rscript` |
|[regtools](https://github.com/griffithlab/regtools#installation) | 0.5.1 | `regtools` |
|[RSeQC](http://rseqc.sourceforge.net/#installation) | 3.0.1 | `bam2wig.py`|
|[salmon](http://salmon.readthedocs.io/en/latest/building.html) | 1.2.1 | `salmon` |
|[samtools](http://www.htslib.org/download/) | 1.10 | `samtools` |
|[SubRead](http://bioinf.wehi.edu.au/subread-package/) | 2.0.0 | `featureCounts` |
|[trimmomatic](http://www.usadellab.org/cms/?page=trimmomatic) | 0.39 | `java -jar path/to/trimmomatic.jar` |
|[wiggletools](https://github.com/Ensembl/WiggleTools) | 1.2.1 | `wiggletools` |
|[wigToBigWig](http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/) | 4 | `wigToBigWig` |

## Docker Images

The following container versions are used in this pipeline. These are automatically managed by SPEAQeasy.

| Image | Tag | Software |
|:-------------:| -----:| -----: |
| libddocker/r_3.6.1_bioc | latest | R and Bioconductor 3.10 |
| libddocker/ubuntu16.04_base | 1_v3 | Ubuntu Base |
| libddocker/infer_strandness | latest | R, Bioconductor 3.10, Kallisto |
| libddocker/kallisto | 0.46.1 | Kallisto |
| libddocker/fastqc | 0.11.8  | FastQC |
| libddocker/trimmomatic | 0.39 | Trimmomatic |
| libddocker/hisat2 | 2.2.1 | HISAT2 |
| libddocker/rseqc | 3.0.1 | RSeQC |
| libddocker/samtools | 1.10 | Samtools |
| libddocker/salmon | 1.2.1 | Salmon |
| libddocker/regtools | 0.5.1 | Regtools |
| libddocker/subread | 2.0.0 | SubRead/FeatureCounts |
| libddocker/wiggletools-1.2 | 1_v3 | Wiggletools |
| libddocker/variant_calling | 1.10.2 | Samtools, BCFTools |
